version: '3.3'
services:
  postgresql:
    container_name: postgresql
    build: ./docker/
    restart: always
    ports:
      - "54321:5432"
    environment:
      POSTGRES_DB: books_authors
      POSTGRES_USER: books_authors
      POSTGRES_PASSWORD: books_authors
    volumes:
      - ./docker/data:/var/lib/postgresql/data